name: Chad's Daily Commit

on:
  schedule:
    - cron: '0 2 * * *'  # Every day at midnight

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
   - name: Copy current save to repository
      run: |
        cp /home/steam/.config/Epic/satisfactory/SavedGame/server/fomo_autosave_2.sav ./

    - name: Create file and commit
      run: |
        FILE="commit_number.md"
        git config --global user.name "itsallvoodoo"
        git config --global user.email "general@itsallvoodoo.com"
        git add .
        git commit -m "Updating save file from server"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/itsallvoodo/satisfactory-saves.git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
